# Generated by Django 4.2 on 2023-04-24 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_remove_cartitem_user_cart_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="created_at",
        ),
    ]
