# Generated by Django 4.2 on 2023-04-24 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_app",
            "0005_product_remove_cartitem_name_remove_cartitem_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
