# Generated by Django 4.2 on 2023-04-26 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0008_deliverylocation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverylocation",
            old_name="address",
            new_name="delivery_address",
        ),
    ]
