# Generated by Django 4.2 on 2023-04-27 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0010_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
