# Generated by Django 4.2 on 2023-04-28 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0013_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
