# Generated by Django 4.2 on 2023-04-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0015_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="selected_card",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.bankcard",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="selected_delivery_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.deliverylocation",
            ),
        ),
    ]
