# Generated by Django 4.2 on 2023-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0016_order_selected_card_order_selected_delivery_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="scanning",
            new_name="cross_processing",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="quantity",
            new_name="film_count",
        ),
        migrations.RemoveField(
            model_name="order",
            name="film_format",
        ),
        migrations.RemoveField(
            model_name="order",
            name="processing_type",
        ),
        migrations.RemoveField(
            model_name="order",
            name="selected_card",
        ),
        migrations.RemoveField(
            model_name="order",
            name="selected_delivery_location",
        ),
        migrations.AddField(
            model_name="order",
            name="border_style",
            field=models.CharField(
                choices=[("noBorders", "noBorders"), ("whiteBorders", "whiteBorders")],
                default="noBorders",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="do_not_cut_negatives",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="film_type",
            field=models.CharField(
                choices=[("35mm", "35mm"), ("120mm", "120mm")],
                default="35mm",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="number_of_copies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="paper_type",
            field=models.CharField(
                choices=[("glossy", "glossy"), ("matte", "matte")],
                default="glossy",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="print_size",
            field=models.CharField(
                choices=[
                    ("9x13", "9x13"),
                    ("10x15", "10x15"),
                    ("13х13", "13х13"),
                    ("13х18", "13х18"),
                    ("13х30", "13х30"),
                    ("15х15", "15х15"),
                    ("15х21", "15х21"),
                    ("15х30", "15х30"),
                    ("20х20", "20х20"),
                    ("20х30", "20х30"),
                ],
                default="9x13",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="print_type",
            field=models.CharField(
                choices=[("color", "color"), ("bw", "bw")],
                default="color",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="push_pull",
            field=models.CharField(
                choices=[("Push", "Push"), ("Pull", "Pull"), ("", "None")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="scan_size",
            field=models.CharField(
                choices=[("L", "L"), ("XL", "XL"), ("XXL", "XXL")],
                default="L",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="slide_film_processing",
            field=models.BooleanField(default=False),
        ),
    ]
